name: "external API action"
description: "use an external API to retrive and display joke"

outputs:
  joke-output:
    description: "The resulting joke from the API"

runs:
  using: node16
  main: main.js
