name: "JS Actions"
on: 
  pull_request:
    types: [labeled]
  push:

jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: "hello-action"
    job2:
      runs-on: ubuntu-latest
      steps:
        - uses: ./.github/actions/hello-world
          with:
            first-greeting: "Learning Lab User"
            second-greeting: "Amanda and her sister"
            third-greeting:  "Caroline"
    job3:
      runs-on: ubuntu-latest
      steps:
        - name: jokes
          uses: ./.github/actions/joke-action
        - name: "create-issue"
          uses: ./.github/actions/issue-maker
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            issue-title: "** RANDOM title **"
            joke: echo ${{ steps.jokes.outputs.joke-output }}

