name: "JS Actions"
on: 
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Learning Lab User"
          second-greeting: "Amanda and her sister"
          third-greeting:  "Caroline" 
      - name: "buhahaha"
        uses: ./.github/actions/joke-action
      - name: "create-issue"
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.buhahaha.outputs.joke-output}}
