name: "JS Actions"
on: 
  pull_request:
    types: [labeled]
  push:

jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: "hello-action"
          uses: ./.github/actions/hello-world
          with:
            first-greeting: "Learning Lab User"
            second-greeting: "Amanda and her sister"
            third-greeting:  "Caroline"
          
    job2:
      runs-on: ubuntu-latest
      outputs:
        out1: ${{ steps.joke }}
        out2: ${{ steps.joke.outputs.joke-output}}
        out3: ${{ steps.joke.outputs.joke-output}}
      steps:
       - uses: actions/checkout@v1
       - id: joke
         uses: ./.github/actions/joke-action
         
         
    job3:
      runs-on: ubuntu-latest
      needs: job2
      steps:
        - uses: actions/checkout@v1
        - name: "create-issue"
          uses: ./.github/actions/issue-maker
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            issue-title: "** RANDOM title **"
            joke: ${{ needs.job2.outputs.out1 }} ${{ needs.job2.outputs.out2 }} ${{ needs.job2.outputs.out3 }}
        - run: node main.js


